BUILDINGMAP = {
    "Atki": "Atkins Library",
    "AtkiG": "Atkins Library",
    "AtkiL": "Atkins Library",
    "Band": "Johnson Band Center",
    "BandCor": "Johnson Band Center",
    "Barn": "Barnard",
    "BelG": "Belk Gym",
    "BelGGym": "Belk Gym",
    "BelGMain": "Belk Gym",
    "BelGPool": "Belk Gym",
    "BelGRB": "Belk Gym",
    "BelH": "Belk Hall",
    "Bioi": "Bioinformatics",
    "BioiVEST": "Bioinformatics",
    "Burs": "Burson",
    "BursBOIL": "Burson",
    "CRI": "CRI",
    "Came": "Cameron Hall",
    "Cato": "Cato Hall",
    "Ceda": "Cedar Hall",
    "CoEd": "College Of Education",
    "Colv": "Covald",
    "Cone": "Cone Center",
    "Coun": "Price Counseling Center",
    "Denn": "Denny",
    "Duke": "Duke Hall",
    "EPIC": "Epic Building",
    "EPICG": "Epic Building",
    "Fret": "Fretwell",
    "Frid": "Friday",
    "Gari": "Garinger Building",
    "Grig": "Grigg Hall",
    "Heal": "College Of Health And Human Services",
    "HealCOR": "College Of Health And Human Services",
    "Hick": "Hickory Hall",
    "Hous": "Housing and Residence Life",
    "HunH": "Hunt Hall",
    "Kenn": "Kennedy",
    "King": "King",
    "Laur": "Laurel Hall",
    "Levi": "Levine Hall",
    "Lync": "Lynch Hall",
    "MSII": "Motorsports Research",
    "Macy": "Macy",
    "Mart": "Martin Hall",
    "McEn": "McEniry",
    "McMi": "McMillan Greenhouse",
    "Memo": "Memorial Hall",
    "MilH": "Miltimore Hall",
    "MiltA": "Miltimore‐Wallis Center",
    "Moto": "Motorsports Research",
    "PORT": "PORTAL",
    "PORTCOR": "PORTAL",
    "PROS": "Prospector",
    "Pros": "Prospector",
    "Rees": "Reese",
    "Robi": "Robinson Hall",
    "Rowe": "Rowe",
    "Smit": "Smith",
    "Stor": "Storrs",
    "StorCOR": "Storrs",
    "Storr": "Storrs",
    "StuA": "Student Activitis Center",
    "StuH": "Student Health Center",
    "StuU": "Student Union",
    "Winn": "Winningham",
    "With": "Witherspoon",
    "Wood": "Woodward"
}